Description = anthra
clrChannelBackground = B012273f
clrChannelBackBlend = B0858585

clrChannelHead = FFFFFFFF
clrChannelEPG = FFFFFFFF
clrChannelEPGInfo = FFFFFFFF
clrChannelEPGNext = FFFFFFFF
clrChannelEPGInfoNext = FFFFFFFF
clrChannelProgressBar = FF333333
clrChannelProgressBarBack = FFFFFFFF
clrChannelProgressBarBlend = FF7D7D7D
clrStatusIconsBack = 00000000
clrRecNow = DDFF0000
clrRecNowFont = FFFFFFFF
clrRecNext = DDFFFF00
clrRecNextFont = FF000000

clrReplayBackground = AA353B4E 
clrReplayBackBlend = B0858585
clrReplayHead = FFFFFFFF
clrReplayDescription = FFFFFFFF
clrReplayCurrentTotal = FFFFFFFF
clrReplayProgressSeen = FF7D7D7D
clrReplayProgressRest = FFFFFFFF
clrReplayProgressSelected = FF000000
clrReplayProgressMark = FF000000
clrReplayProgressError = FF0000FF
clrReplayProgressCurrent = 90FFFFFF
clrReplayHighlightIcon = FFFFD700

clrTracksFontHead = FF858585
clrTracksFontButtons = FFFFFFFF
clrVolumeFont = FFFFFFFF
clrMenuBack = 00000000
clrMenuBorder = 00000000
clrMenuScrollBar = 900000FF
clrMenuScrollBarBack = 99000000 
clrMenuScrollBarBase = 00000000
clrMenuItem = 7D000000
clrMenuItemBlend = 64000000
clrMenuItemHigh = 7D000000
clrMenuItemHighBlend = FE999999
clrSeparatorBorder = EE444444
clrDiskAlert = 90cc0000
clrTimersBack = 7D000000 
clrTimersBackBlend = FE999999
#############################
clrMenuFontHeader = FFFFFFFF
clrMenuFontDate = FFFFFFFF
###################################
clrMenuFontDiscUsage = FFFFFFFF
clrMenuFontTimers = FFFFFFFF
clrMenuFontTimersHeader = FFFFFFFF
clrMenuFontDetailViewText = FFFFFFFF
clrMenuFontDetailViewHeader = FF858585
clrMenuFontDetailViewHeaderTitle = FFFFFFFF
clrMenuFontMenuItem = FFFFFFFF
#####################
clrMenuFontMenuItemHigh = FFFFFFFF
clrMenuFontMenuItemTitle = FFFFFFFF
clrMenuFontMenuItemSep = FFFFFFFF
##################
clrMenuHeader = DD000000
clrMenuHeaderBlend = 60FFFFFF
clrAudioMenuHeader = DD000000
####
clrProgressBar = FF7D7D7D
clrProgressBarBack = FFFFFFFF
clrProgressBarBlend = FF333333
clrProgressBarHigh = FF7D7D7D
clrProgressBarBackHigh = DD000000
clrProgressBarBlendHigh = FF7D7D7D

clrMenuTextWindow = B0000000
clrMenuChannelLogoBack = 7DFFFFFF
clrButtonRed = 99BB0000
clrButtonRedBorder = FFBB0000
clrButtonRedFont = FFFFFFFF
clrButtonGreen = 9900BB00
clrButtonGreenBorder = FF00BB00
clrButtonGreenFont = FFFFFFFF
clrButtonYellow = 99BBBB00
clrButtonYellowBorder = FFBBBB00
clrButtonYellowFont = FFFFFFFF
clrButtonBlue = 990000BB
clrButtonBlueBorder = FF0000BB
clrButtonBlueFont = FFFFFFFF
clrMessageFontStatus = FFFFFFFF
clrMessageFontInfo = FFFFFFFF
clrMessageFontWarning = FFFFFFFF
clrMessageFontError = FFFFFFFF
clrMessageStatus = 9000BBFF
clrMessageInfo = 90009900
clrMessageWarning = 90BBBB00
clrMessageError = 90BB0000
clrMessageBlend = DD000000
clrMenuDetailViewTabs = DD0000ad
